export default {
    // 登录
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    // 通知
    RECIVE_NOTIFICATIONS:'RECIVE_NOTIFICATIONS',
    NOTIFICATION_POST_START:'NOTIFICATION_POST_START',
    NOTIFICATION_POST_END:'NOTIFICATION_POST_END',
    MARK_NOTIFICATION_AS_READ_BY_ID:'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ:'MARK_ALL_NOTIFICATIONS_AS_READ',
    // 首页-项目
    GET_PROJECTS_START:'GET_PROJECTS_START',
    GET_PROJECTS_SUCCESS:'GET_PROJECTS_SUCCESS',
    GET_PROJECTS_FAILED:'GET_PROJECTS_FAILED',
    PROJECT_CHANGE:'PROJECT_CHANGE',
    // 个人设置 
    CHANGE_INPUT_VALUE:'CHANGE_INPUT_VALUE'
}